name = "seaportoquiz"
main = "main.js"
compatibility_date = "2025-10-29"

[[kv_namespaces]]
binding = "sp_quiz"
id = "70359524ede84ec688760c0b20b0dfad"

[[kv_namespaces]]
binding = "sp_results"
id = "612d330a6d604cda99ae7af0ab8f03b6"

[logs]
level = "info"
enabled = true

[observability.logs]
enabled = true
